package com.orange.jbpm_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BillingAccount implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public BillingAccount() {
    }




}