package com.orange.jbpm_poc;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({
"id",
"href",
"name"
})
public class ProductInventory implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "PRODUCTINVENTORY_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(sequenceName = "PRODUCTINVENTORY_ID_SEQ", name = "PRODUCTINVENTORY_ID_GENERATOR")
    private java.lang.Long id;

    public ProductInventory() {
    }
    
    public ProductInventory(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }




}